### ISSUE TITLE
question: Could you add a rss/atom feed ?

### ISSUE THREAD

**Issue by IrrenWirr** [benjamin-asdf/faster-than-light-memes#1]
[RSS](https://en.wikipedia.org/wiki/RSS) or [atom](https://en.wikipedia.org/wiki/Atom_(web_standard)) feeds are really useful for following/subscribing blogs.
I would really appreciate (And I believe others would too) if you could turn on feeds on blog.

I never did this myself and don't know how hard/easy is it to do but [here goes a link describing how to enable it for GitHub pages](https://dzhavat.github.io/2020/01/19/adding-an-rss-feed-to-github-pages.html).

**Comment by benjamin-asdf** [comment]
https://benjamin-asdf.github.io/faster-than-light-memes/
I have now implemented an atom feed and a clojure only atom feed. 
Thank you for your interest in my memes.
https://benjamin-asdf.github.io/faster-than-light-memes/atom.xml
https://benjamin-asdf.github.io/faster-than-light-memes/planetclojure.xml
